### ISSUE TITLE
"Dialog Team ID verification" Error Message

### ISSUE THREAD

**Issue by deadly-muffin** [robjschroeder/App-Auto-Patch#10]
Product appears to be functional, but users can receive an error message
"Please advise your Support Representative of the following error:"
"Dialog Team ID verification failed"
(Close button)
We have been instructing users to hit Close.
However, I have seen the product function and update apps.
Not sure what is causing the "error" dialog message.  Is this something I can configure to remove/hide/ignore/resolve the error message?  Thank you!!

**Comment by robjschroeder** [comment]
Fixed with the latest commit. Thank you @deadly-muffin !
