### ISSUE TITLE
Multiple Request

### ISSUE THREAD

**Issue by mani2care** [robjschroeder/App-Auto-Patch#2]
Hi , This is really great solution for us as a beginner i tried testing you script its work really good. but its not giving as expected results, can you help me to correct this.
1) Application Icon not showing Nudge, MSAutoupdater it may i did not tested all the application.
2) As per the parameter i defined to install only the Nudge but still its scan all the application is that possible to define the rule like in parameter --"scan the system and install all the application update pending" / or specified parameter App1 App2 ..
3) As same as the other parameter restriction restrict all only exclude only specified application if necessary....
4) i noticed the application installation count is showing wrong must be catalog item how many is installed or failed. if applicable.

what you think so is its just my test results.    

<img width="439" alt="image" src="https://github.com/robjschroeder/App-Auto-Patch/assets/52978899/79bfb930-4421-498b-8042-f346548d608c">

<img width="515" alt="image" src="https://github.com/robjschroeder/App-Auto-Patch/assets/52978899/e08fcef0-35a8-467c-95e2-a449b6dbed14">

<img width="923" alt="image" src="https://github.com/robjschroeder/App-Auto-Patch/assets/52978899/f3dc4f42-f5f1-4424-a479-d2aace32e41d">

**Comment by robjschroeder** [comment]
Hey @mani2care, 

1. For the app icon, this is getting pulled from the installed path of the app, it is assuming: 
icon: /Applications/${currentDisplayName}.app

If that is not where the app is located, the icon will not be properly associated. 

2. The parameter for required apps does not limit to that list. Instead it makes sure that the app(s) listed will be installed if they are not. For instance, if you require that nudge be installed on your computers, you can put nudge in the required list and if that computer doesn't already have nudge, it will install it. 

3. This parameter is used to exclude any labels if you'd like. For example, you can see that there are multiple labels associated with the Zoom app. You may want to exclude the labels that don't pertain to your deployment to make sure you are deploying the correct package. 

4. This is definitely an issue that has been created: Issue #4 , I've recently commented the line out that displays this for now on verison 1.0.11.
