### ISSUE TITLE
Some things to consider...

### ISSUE THREAD

**Issue by wakco** [robjschroeder/App-Auto-Patch#25]
1. ~~Line 401 the word Path is showing twice, so the `rm` command removes nothing,~~(fixed in v2, however...) which ~~is~~was good in my case as I have Installomator installed anyway, and don't want it removed, instead, I'd like to suggest providing an option for us to decided to keep or remove Installomator.  Removing the tar file after it has been decompressed might be a good idea (since it ~~isn't~~wasn't, but this is also technically fixed by how Installomator is removed in v2).
2. Since Installomator has a label for swiftDialog, why not just use that instead of doing the same code again? Might also want to treat it as an always ignore as well, to avoid any issue that might arise from updating it, while using it.
3. The name, can we allow for customising the name, as I do not see the average user understanding what "App Auto-Patch" is, even if they started it themselves from Self Service.

In my copy I'm working on providing in our Jamf instance, I've renamed it to "Installed Applications Updater", and removed the function and calls thereto for removing Installomator, while adding a line to the end of the downloadLatestLabels function to remove the tar file (I checked, the only use of this file is in this function and it's only needed to download and decompress). But everything else is great.

**Comment by wakco** [comment]
And now I notice version 2, guess I should check how tat is different.

**Comment by robjschroeder** [comment]
Hey @wakco ! Thanks for the feedback, I'm hoping to get out a version 2 RC soon. I will take a look at these suggestions deeper tomorrow. Thanks again!

**Comment by robjschroeder** [comment]
Hey @wakco please feel free to check out version 2.0.0b11. Thank you!
