### ISSUE TITLE
Using for intune managed MacOS devices?

### ISSUE THREAD

**Issue by sultanberisa** [robjschroeder/App-Auto-Patch#29]
Hello. We use intune for managing our MacOS devices and would be really cool to use your script, i've tested it on a mac and seems to work great. Great job on this!

Wondering if you have any ideas for deploying this to MacOS managed devices? We can ofcourse deploy the script itself, but we would like some sort of the data (maybe the log it generates) pushed back to us in order to recieve some sort of status or log back to ensure that there were no errors, and X or Y was successfully patched and so forth.

Any ideas here?

**Comment by robjschroeder** [comment]
Would something like this work for you? 

Login on Microsoft Intune admin center.
Click on Devices > macOS >Shell scripts.
Click on any Script deployment name.
Go to either Device status or User status under Monitor.
Click on the Device Name or User name > A Pane will open on the right-hand side.
Click on Collect logs.

You’ll need the absolute path to the log file to collect, but this would be one way. 

We currently don’t enroll our computers into Intune so I can’t verify or know if this action can be automated or added onto your #app-auto-patch script deployment. 

Additionally, depending on how deep you want to go, you could either have a Teams integrated webhook to send you failures or successes (there’s a good example of this in #setup-your-mac), or maybe a PowerAutomate webhook workflow, sending your logs to PA and getting them where they need after that. For questions on that you can check the #webhooks channel
