### ISSUE TITLE
Feature Request: Having a label array where you define which apps should be updated exclusively

### ISSUE THREAD

**Issue by yanhoos** [robjschroeder/App-Auto-Patch#32]
I have evaluated App Auto-Patch in our Jamf environment and noticed that all apps found on the Mac are updated and installed. For example, if there are apps in the Downloads folder or in a folder other than /Applications and /Applications/Utilities with pending updates, they are also updated or installed by Installomator in the Applications folder.

The required label can only be used to define which apps must be installed; if they are not found, they will still be installed.

I'm thinking of something similar with the feature request, e.g. a label array where you define which apps should be updated exclusively. In other words, the opposite of the ignored label.

Apart from the point mentioned, it is a very helpful tool for keeping the Mac fleet up to date in terms of the installed applications without creating and handling a lot of Jamf update policies. Many thanks!

**Comment by grahamr** [comment]
Also, just to clarify, the difference here from Required is that if the app is NOT installed it won't be installed right? 

EG: Force update Chrome, Edge, Firefox, VS Code - and if a user doesn't have Firefox they wouldn't get it?

**Comment by PringelsxDz** [comment]
+1 

This will be a great functionality that we can use. Just required labels for applications that are installed, so that we can force this to run end of each month.

**Comment by robjschroeder** [comment]
This should be covered with the last merge #35
