### ISSUE TITLE
Feature Request: Dropdown to view available updates for deferral window

### ISSUE THREAD

**Issue by mobofixer** [robjschroeder/App-Auto-Patch#47]
It would be great to have a dropdown on the deferral screen so users can make informed decisions on what apps they are deferring until the script runs again. 
![image (1)](https://github.com/robjschroeder/App-Auto-Patch/assets/96198719/098b793a-f6d4-45a9-ba82-10b22d53d0b7)

**Comment by robjschroeder** [comment]
This will be part of #50
