### ISSUE TITLE
Feature Request: Nudge and Deferral 

### ISSUE THREAD

**Issue by northalpha** [robjschroeder/App-Auto-Patch#9]
I really would like to have a possibility for the Enduser to defer the Updates because reasons. I like the way https://github.com/avogel-mac/Patch-Helper implemented this, maybe a good starting point for integration?

Also would be nice to make the deferal interval and the deferral counter configurable via policy arguments (2 more args)

**Comment by robjschroeder** [comment]
Deferrals have been added into version 2.0.0!! #35
